apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  labels:
    app: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: fdcontainerregistry1.azurecr.io/fd-ml-image-fast:latest
          ports:
          - containerPort: 80