apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-canary
  template:
    metadata:
      labels:
        app: model-canary
    spec:
      containers:
        - name: model-canary
          image: innovativefrauddetection.azurecr.io/frauddetectionfast:latest
          ports:
          - containerPort: 80