apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
        - name: model
          image: innovativefrauddetection.azurecr.io/frauddetectionfast:13
          ports:
          - containerPort: 80